### ISSUE TITLE
microprofile-schedule on Payara fails when following docs

### ISSUE THREAD

**Issue by karianna** [microprofile/microprofile-conference#102]
Followed the steps to get the microservice-schedule service up and running:

```
cd microservice-schedule
mvn clean package
java -jar target/microservice-schedule.jar
```

And then go to http://localhost:8080/microservice-schedule/schedule/1 but get a 404

Then tried a different port, e.g.

`java -jar target/microservice-schedule.jar --port 9050`

And then go to http://localhost:9050/microservice-schedule/schedule/1 but get a 404

**Comment by katheris** [comment]
The docs currently state to go to http://localhost:6060/schedule/all this works for me. Are you happy to close this issue?

**Comment by karianna** [comment]
Yes - now works for me with the new instructions
