### ISSUE TITLE
3 x SessionVoteTest failures

### ISSUE THREAD

**Issue by karianna** [microprofile/microprofile-conference#110]
Tests in error:
  SessionVoteTest.testDeleteRating:186 » NullPointer
  SessionVoteTest.testRateSession:146 NullPointer
  SessionVoteTest.testUpdateRating:162 » NullPointer

**Comment by lasombra** [comment]
I'm looking into this. It seems CDI is not kicking in, making `HashMapSessionRatingDAO`'s `@Inject` not working and also `init()`.

WDYT of running this test on Arquillian?

**Comment by karianna** [comment]
Tests are good :-)
