### ISSUE TITLE
Schedule Service pom will need to use Payara microprofile version

### ISSUE THREAD

**Issue by smillidge** [microprofile/microprofile-conference#13]
Note to self!
Currently the schedule service uses Payara Micro as a dependency. When we have a microprofile version on maven central then the pom dependencies will need correcting.

**Comment by mikecroft** [comment]
The schedule service deploys and creates the Uber JAR correctly, but there is a problem with the service itself. It currently uses JAXB in the adapter classes for marshalling e.g. dates, so this will need to be removed/reworked/something to make it spec-compliant.

(works beautifully on Payara Micro though ;-)

**Comment by mikecroft** [comment]
tagging @ivannov FYI.
I've got a build of the Payara microprofile locally, let me know if you want me to upload it somewhere so you've got something to verify on before it gets into Maven Central. (I think it should be there very soon anyway)

**Comment by mikecroft** [comment]
...just noticed [the discussion RE: JAXB being in Java SE on the microprofile group[(https://groups.google.com/d/msg/microprofile/eESKpfPmguc/X6800CBBDQAJ). The error is a ClassNotFound exception looking for Jackson, so it's probably an artifact of building it against Payara Micro :)

oops!
