### ISSUE TITLE
Full build fails with web-application module error

### ISSUE THREAD

**Issue by heiko-braun** [microprofile/microprofile-conference#28]
[INFO] ------------------------------------------------------------------------
[INFO] Building Conference :: Web 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ web-application ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install-node-and-npm) @ web-application ---
[INFO] Node v6.5.0 is already installed.
[INFO] NPM 3.10.7 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:npm (npm-install) @ web-application ---
[INFO] Running 'npm install' in /Users/hbraun/dev/prj/microprofile-conference/web-application/src/main/static
[INFO] 
[INFO] > microprofile-conference@1.0.0 postinstall /Users/hbraun/dev/prj/microprofile-conference/web-application/src/main/static
[INFO] > typings install
[INFO] 
[ERROR] sh: typings: command not found
[ERROR] 
[WARNING] npm WARN angular2-in-memory-web-api@0.0.18 requires a peer of @angular/core@2.0.0-rc.6 but none was installed.
[WARNING] npm WARN angular2-in-memory-web-api@0.0.18 requires a peer of @angular/http@2.0.0-rc.6 but none was installed.
[WARNING] npm WARN angular2-in-memory-web-api@0.0.18 requires a peer of rxjs@5.0.0-beta.11 but none was installed.
[ERROR] npm ERR! Darwin 15.6.0
[ERROR] npm ERR! argv "/Users/hbraun/.microprofile/node-installation-dir/node/node" "/Users/hbraun/.microprofile/node-installation-dir/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v6.5.0
[ERROR] npm ERR! npm  v3.10.7
[ERROR] npm ERR! file sh
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn
[ERROR] npm ERR! microprofile-conference@1.0.0 postinstall: `typings install`
[ERROR] npm ERR! spawn ENOENT
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the microprofile-conference@1.0.0 postinstall script 'typings install'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the microprofile-conference package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     typings install
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs microprofile-conference
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls microprofile-conference
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /Users/hbraun/dev/prj/microprofile-conference/web-application/src/main/static/npm-debug.log
[INFO] ------------------------------------------------------------------------

**Comment by heiko-braun** [comment]
As a workaround, exclude the web module:

```
mvn clean -DskipTests=true -pl \!web-application install
```

**Comment by heiko-braun** [comment]
Any node/web/js folks around that can interpret the error?

**Comment by karianna** [comment]
It's typically a sudo issue with node/npm and Mac OS X.  old corrupt
artifacts get left in node_modules and node folders

Probably best if we screenshare over this.

Cheers,
Martijn

**Comment by AndyGee** [comment]
cd web-application/src/main/static
npm install npm
npm install typings --global
typings install --global

Ignore warnings

**Comment by kenfinnigan** [comment]
@AndyGee beat me to it!

I had the same error until I installed typings.

I'm going to update the readme to make the prereqs clearer

**Comment by heiko-braun** [comment]
Thanks @AndyGee and @karianna . It's been a the permission problem as you said.
