### ISSUE TITLE
A provided dependency which is not available in MicroProfile

### ISSUE THREAD

**Issue by OndrejM** [microprofile/microprofile-conference#69]
At the last commit (in master) https://github.com/microprofile/microprofile-conference/blob/4c200c89b3f34124959500564df0bb2a4f7c51ea/demo-bootstrap/pom.xml#L50, there is `provided` dep on commons-lang3 in demo-bootstrap, which is not available in every MicroProfile runtime. It needs to be turned to `compile` dependency or removed altogether.

**Comment by AndyGee** [comment]
Probably easiest to remove - It's only used for the .toString() - Which vendor doesn't provide it?

**Comment by OndrejM** [comment]
Payara does not include, and even if it does, it is better to remove it, as it is not in mP anyway.

**Comment by kenfinnigan** [comment]
Fixed by https://github.com/microprofile/microprofile-conference/pull/70
