### ISSUE TITLE
Cannot build the microprofile-conference

### ISSUE THREAD

**Issue by SvetlinZarev** [microprofile/microprofile-conference#88]
The microprofile-conference project cannot be build due to unsatisfiable dependency
```

[INFO] Reactor Summary:
[INFO]
[INFO] Conference ........................................ SUCCESS [0.262s]
[INFO] Conference :: Bootstrap Data ...................... SUCCESS [3.055s]
[INFO] Conference :: Session ............................. FAILURE [0.577s]
[INFO] Conference :: Vote ................................ SKIPPED
[INFO] Conference :: Vote :: Application ................. SKIPPED
[INFO] Conference :: Vote :: Config ...................... SKIPPED
[INFO] Conference :: Speaker ............................. SKIPPED
[INFO] Conference :: Speaker :: Model .................... SKIPPED
[INFO] Conference :: Speaker :: Web ...................... SKIPPED
[INFO] Conference :: Schedule ............................ SKIPPED
[INFO] Conference :: Web ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.285s
[INFO] Finished at: Tue Oct 25 15:12:43 EEST 2016
[INFO] Final Memory: 25M/124M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project microservice-session: Could not resolve dependencies for project io.microprofile.showcase:microservice-session:war:1.0.0-SNAPSHOT: Failure to find org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1....
```

**Comment by katheris** [comment]
What version of maven are you using as I ran into some issues with Wildfly Swarm that were resolved by updating my maven version. Also what command are you using to build the app? mvn install or mvn package?

**Comment by SvetlinZarev** [comment]
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 15:51:28+0200)

The command is "mvn clean install"

**Comment by katheris** [comment]
I'm running with 3.2.5, can you try updating and see if it still occurs?

**Comment by kenfinnigan** [comment]
WildFly Swarm requires a minimum of Maven 3.2.5 unfortunately.

**Comment by SvetlinZarev** [comment]
Thanks, with maven 3.3.9 the build finished successfully :) What do you think about adding a maven enforcer rule to check the minimum mvn version ? Then the error message would be something like: "Detected Maven Version: 3.3.9 is not in the allowed range [3.2.5,Whatever)."

**Comment by kenfinnigan** [comment]
Probably not a bad idea.

Could you create a new issue and close this one?

Thanks

**Comment by SvetlinZarev** [comment]
Sure :)

**Comment by AndyGee** [comment]
Really only need this in parent pom:
`
<prerequisites>
   <maven>3.2.3</maven>
</prerequisites>
`

**Comment by dwamara** [comment]
Have exactly this issue using Maven 3.3.9 and Nexus as artefacts repository. Any idea on how to fix it?

**Comment by Turbots** [comment]
The versions of these dependencies seem really weird, why are they requiring versions with jbossorg-1? These are not available in the public Maven repositories. I cannot build any of the samples either because of this.
